name: Update Data Otomatis
on:
  schedule:
    - cron: '0 * * * *' # Berjalan setiap jam
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run Scraper
        run: python scraper.py
      - name: Commit and Push
        run: |
          git config --global user.name 'Scraper Bot'
          git config --global user.email 'bot@github.com'
          git add data.txt
          git commit -m "Update data otomatis" || exit 0
          git push
